# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TranslationFromOneNumberSystemToAnotherWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(570, 330)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS,Comic Sans,cursive")
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QWidget {\n"
"    color: white;\n"
"    background-color: #abb8c3;\n"
"    font-weight: 600;\n"
"    font-family: Comic Sans MS, Comic Sans, cursive;\n"
"\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #abb8c3;\n"
"    border: 2px solid rgb(198, 0, 0);\n"
"    color: #000;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(198, 0, 0);\n"
"    color: #fff;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(191, 0, 0);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(20, 20, 150, 30))
        self.label_1.setStyleSheet("color: #000;")
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 441, 51))
        self.label_2.setStyleSheet("color: #000;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 441, 71))
        self.label_3.setStyleSheet("color: #000;")
        self.label_3.setObjectName("label_3")
        self.lbl_number = QtWidgets.QLineEdit(self.centralwidget)
        self.lbl_number.setGeometry(QtCore.QRect(180, 20, 300, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS,Comic Sans,cursive")
        font.setBold(True)
        font.setWeight(75)
        self.lbl_number.setFont(font)
        self.lbl_number.setStyleSheet("color: #000;")
        self.lbl_number.setObjectName("lbl_number")
        self.sb_system_first = QtWidgets.QSpinBox(self.centralwidget)
        self.sb_system_first.setGeometry(QtCore.QRect(480, 70, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS,Comic Sans,cursive")
        font.setBold(True)
        font.setWeight(75)
        self.sb_system_first.setFont(font)
        self.sb_system_first.setStyleSheet("color: #000;")
        self.sb_system_first.setMinimum(2)
        self.sb_system_first.setMaximum(36)
        self.sb_system_first.setObjectName("sb_system_first")
        self.sb_system_second = QtWidgets.QSpinBox(self.centralwidget)
        self.sb_system_second.setGeometry(QtCore.QRect(480, 140, 80, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS,Comic Sans,cursive")
        font.setBold(True)
        font.setWeight(75)
        self.sb_system_second.setFont(font)
        self.sb_system_second.setStyleSheet("color: #000;")
        self.sb_system_second.setMinimum(2)
        self.sb_system_second.setMaximum(36)
        self.sb_system_second.setObjectName("sb_system_second")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 270, 150, 30))
        self.label_4.setStyleSheet("color: #000;")
        self.label_4.setObjectName("label_4")
        self.lbl_end_number = QtWidgets.QLineEdit(self.centralwidget)
        self.lbl_end_number.setGeometry(QtCore.QRect(180, 270, 300, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS,Comic Sans,cursive")
        font.setBold(True)
        font.setWeight(75)
        self.lbl_end_number.setFont(font)
        self.lbl_end_number.setStyleSheet("color: #000;")
        self.lbl_end_number.setObjectName("lbl_end_number")
        self.btn_convert = QtWidgets.QPushButton(self.centralwidget)
        self.btn_convert.setGeometry(QtCore.QRect(175, 210, 220, 40))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS,Comic Sans,cursive")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_convert.setFont(font)
        self.btn_convert.setStyleSheet("font-size: 12px;")
        self.btn_convert.setObjectName("btn_convert")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Перевод числа в системы счисления"))
        self.label_1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Введите число:</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Введите систему счисления этого числа:</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Введите систему счисления, в которой</span></p><p><span style=\" font-size:14pt;\">хотите записать это число:</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Ваше число:</span></p></body></html>"))
        self.btn_convert.setText(_translate("MainWindow", "Перевести"))
